import { Geist, Geist_Mono } from "next/font/google";
import localFont from 'next/font/local';
import "./globals.css";


const bladeRounded = localFont({ 
  src: '../../public/fonts/Bladerounded-Regular.ttf',
  variable: '--font-blade-rounded',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${bladeRounded.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
